name: Congrats!
run-name: Congrats!
on: 
    pull_request: 
        types: [closed]

jobs:
    comment:
        runs-on: ubuntu-latest
        steps:
            - name: Greetings
              uses: actions/github-script@v5
              with:
                # github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.createComment({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        body: "Congrats! You're project has been merged! Your next step is to schedule a call with Bank to get setup with your OnBoard card!\n\nFind a time [here](https://calendar.google.com/calendar/u/0/appointments/schedules/AcZssZ0pvZ17vB492hU6bVBAFJsYgILdPQr32t5z4LrC7DWHfJDMLGs3A0ca-OfvZe3h6I6FmIuom6mM)"
                    })