name: PR Greeter
run-name: PR Greeter
on:
    pull_request:
        types: [ opened ]

jobs:
    Greetings:
        runs-on: ubuntu-latest
        steps:

            - name: Assign to reviewers
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addAssignees({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        assignees: ['bykevinyang']
                    })

            - name: Label as submission
              uses: actions/github-script@v5
              with:
                github-token: ${{secrets.GITHUB_TOKEN}}
                script: |
                    github.rest.issues.addLabels({
                        issue_number: context.issue.number,
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        labels: ['Submission']
                    })
             
            - name: Greetings
              uses: actions/github-script@v5
              env:
                GITHUB_URL: ${{ github.event.pull_request.comments_url }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                script: |
                    echo $GITHUB_URL

                    GITHUB_HANDLE="bykevinyang"
                    # PR_URL=22
 
                    URL="https://airtable.com/shrRaW9OXoIwUXn1E?prefill_PR=${GITHUB_URL}&hide_PR=true&prefill_Github+Handle=${GITHUB_HANDLE}&hide_Github+Handle=true"

                    echo $URL

                    # BODY="![Orpheus waving](http://rawr.hackclub.com/hyper-dino-wave.gif)\n\n👋 Hey there! Welcome to [OnBoard](https://onboard.hackclub.com/)! We got your submission! We currently have our best and brightest reviewing this PR!\n\nIn the meantime, we'll need your email and photo ID to set you setup with Hack Club Bank! **Can you fill out this [form](${URL})**?\n\nSee you in a bit! Woo!"

                    # REQ_DATA="{\"body\": \"${BODY}\"}"

                    # curl -X POST \
                    #     $GITHUB_URL \
                    #     -H "Content-Type: application/json" \
                    #     -H "Authorization: token $GITHUB_TOKEN" \
                    #     --data "$REQ_DATA"