name: PR Greeter
run-name: PR Greeter
on:
  # Trigger the workflow on push or pull request
  pull_request:
     types: [opened]

jobs:
  Comment-on-PR:
    runs-on: ubuntu-latest
    steps:
        - name: Hey There!
          uses: actions/github-script@v5
          with:
            #   github-token: ${{secrets.ONBRDER_TOKEN}}
            script: |
                github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '👋 Hey there! Welcome to OnBoard!'
                })