name: PR Check
run-name: PR Check
on: 
    pull_request: 
        types: [opened]

jobs:
  Check-for-files:
    name: Check for files
    runs-on: ubuntu-latest
    steps:
        - name: Check out
          uses: actions/checkout@v2

        - name: Begin
          run: |
           URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
           FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
           echo $FILES
        
        - name: Check for README.md
          run: |
            URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
            FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
            if [ echo $FILES | grep -q "README.md" ]; then
                echo "README.md included"
                exit 0
            else
                echo "No README.md"
                exit 1
            fi

        - name: Check for Gerbers
          run: |
            URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
            FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
            if [ echo $FILES | grep -q ".zip" ]; then
                echo "Gerbers included"
                exit 0
            else
                echo "Gerbers included"
                exit 1
            fi
        
        - name: Check for JLCPCB Approval
          run: |
            URL="https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files"
            FILES=$(curl -s -X GET -G $URL | jq -r '.[] | .filename')
            if [ echo $FILES | grep -q ".png" ] || [ echo $FILES | grep -q ".jpeg" ]; then
                echo "Screenshot included"
                exit 0
            else
                echo "Screenshot not included"
                exit 1
            fi